### ISSUE TITLE
Not rebasing url()

### ISSUE THREAD

**Issue by buddyackerman** [scniro/gulp-clean-css#8] opened 2016-07-08 16:27 UTC
Below is my css bundling task.  None of the url() references have been rebased for the destination library.  I tested running cleancss (on the one file that has relative url() statements in it) from the command line and it rebased the urls correctly.  Seems gulp-clean-css is not sending the correct params for rebasing.  I even tried to set those options (i.e. cleanCss({relativeTo: './lib'})) myself but it still didn't work.  The url() paths are not changed at all.

```
var gulp = require('gulp');
var concat = require("gulp-concat"),
    rename = require("gulp-rename"),
    uglify = require("gulp-uglify");
    sequence = require("gulp-sequence"),
    cleanCSS = require('gulp-clean-css');


gulp.task('bundleCSS', function () {
    return gulp.src([
                './Content/bootstrap.css',
                './Content/entypo.css',
                './Content/dricofont.css',
                './Content/font-awesome.css',
                './node_modules/primeui/primeui-ng-all.css',
                './node_modules/primeui/themes/redmond/theme.css',
                './Content/site.css'
    ])
        .pipe(cleanCSS())
        .pipe(concat('cssbundle.min.css'))
        .pipe(gulp.dest('./lib'));
});
```

**Comment by scniro** [comment] 2016-07-08 19:26
I don't fully understand. What is the expected result? It looks like you are trying to minify css files and concat them to one. Is there an issue in your end result file?

**Comment by buddyackerman** [comment] 2016-07-08 21:06
The exepected result is that the paths in the url() should be rebased relative to the destination folder.  If a source file located in the /node_modules/component has the following css definition

    .someClass{ background: url(image/someimage.png); }

then the result of the output file (which is located in the ./lib folder) should be 

    .someClass{ background: url(../node_modules/component/image/someimage.png); }

The output I actually get is unchanged from the input.

If I run cleancss from the command line using the -o parameter like this

    cleancss -o .\lib\theme.min.css .\node_modules\primeui\themes\redmond\theme.css

it will rebase the url() path correctly.

However, your module doesn't use the output parameter because you rely on the gulp.dest() method to determine the output so cleancss doesn't get an output path on which to rebase.  I expected that I could use the relativeTo parameter but it doesn't rebase the url() paths.  Based on tht cleancss documentation, relativeTo only fixes @import urls.

**Comment by buddyackerman** [comment] 2016-07-08 22:10
So, I tried to set the target option and it almost worked but it messed up the path in a bizarre way.  So I looked in you code and I think I've found the problem.  In the index.js file starting on line 26 you have this :

`

    var fileOptions = objectAssign({target: file.path}, options);

    if (fileOptions.relativeTo === undefined && (fileOptions.root || file.path)) {
        fileOptions.relativeTo = path.dirname(path.resolve(options.root || file.path));
    }


`


It's setting the _relativeTo_ option to file.path when _relativeTo_ is not being set as an option by the user.  However, if the _target_ option is set, the relativeTo is still being set and that is causing the path rebasing to get messed up.  So, I changed the if statement to this 

     if (options.target == undefined && fileOptions.relativeTo === undefined && (fileOptions.root || file.path)) 

and it's working.  Now, if the user sets the _target_ option then the _relativeTo_ option will only be set if the user sets that also (which they shouldn't because it really messes up the rebasing logic in cleancss.)

**Comment by scniro** [comment] 2016-09-06 14:14
@buddyackerman @jahumes  Hey there! So, I'm playing with some new stuff for a new version to publish, but I'm not heavy enough of a sourcemap user to really get down to the nitty gritty with the issues yourselves and others are experiencing. I'm trying to make the plugin less opinionated with sourcemaps and other stuff, and letting clean-css under the hood take care of everything.

My initial runs with it seem okay, but I'm wanting some more feedback before I'm confident to publish a new version. I made a new repo with a packaged version, [gulp-clean-css-test](https://github.com/scniro/gulp-clean-css-test). If you'd be willing, please clone this and install the packaged plugin into your project via `npm install ../path/to/this/repo/gulp-clean-css-2.1.0.tgz` and share any results you may have?

I'm also hoping this takes care of the rebasing of the url issue as well, since you mentioned you are getting issues specifically using this wrapper and not the command line. Can you compare the output of the two and share your results?

**Comment by buddyackerman** [comment] 2016-09-14 21:48
@scniro I haven't had time to test the update.  I actually had made some changes to my bundling (for reasons not related to this issue) and that change alleviates this issue (for me).  So, I've got to undo my changes in order to test this.  Maybe I can get to it this week or early next if that's not too late.

**Comment by biomedia-thomas** [comment] 2016-12-06 10:23
I'm not sure if this is related but I have a problem with URLs being rebased twice in some cases. I tracked this down to the following piece of code in gulp-clean-css:
```javascript
var cssFile = buf.toString();
if (file.path) {
    cssFile = {};
    cssFile[file.path] = {styles: buf.toString()};
}
new CleanCSS(fileOptions).minify(cssFile, function (errors, css) {
````
When the path is known, a object (hash) is supplied to the minify function rather than the code itself. However, in this mode, clean CSS will already rewrite the URLs the moment it reads the file sources (See the rewriteUrls call in source-reader.js from clean-css), and then again later because of the rebase/relativeTo/target stuff.

If I comment the if in the above code, and use only the 'target' option set to the destination css file, everything works fine.

**Comment by scniro** [comment] 2016-12-06 17:56
@biomedia-thomas I spent some time changing around a few things and published [gulp-clean-css 2.1.0](https://www.npmjs.com/package/gulp-clean-css). I took your suggestion as well and all seems fine. Could you full this down and let me know if you're squared away?

**Comment by madwizard-thomas** [comment] 2016-12-07 10:27
It still rewrites urls twice. You have removed the if-condition but I meant removing the whole if so that the first argument to the minify function is a string with the contents rather than an object with the filename as a key. As soon as you use an object it will rewrite the URLs twice.
```javascript
var cssContent = file.contents.toString();
new CleanCSS(fileOptions).minify(cssContent, function (errors, css) {
````

**Comment by scniro** [comment] 2016-12-07 13:55
hm, i'd need to think on this for a bit since it breaks a test regarding errors returned from clean-css if I just pass the raw content. For some reason it's not working as expected in the following case...

    var File = require('vinyl');
    var css = new File({
      path: './fixtures/test.css',
      contents: new Buffer('body{')
    });

passing just the raw contents here results in an issue-free operation, however, passing the keyed object results in the correct error being returned...

 > 'Missing \'}\' after \'__ESCAPED_SOURCE_END_CLEAN_CSS__\'. Ignoring.'

Unsure why raw only contents are not triggering the clean-css error 😠

**Comment by madwizard-thomas** [comment] 2016-12-07 15:39
I think that is an issue with the tokenizer in clean-css. When the tokenizer (tokenize.js) does not find a closing bracket when inside a selector block, it will generate an error "Missing '}' after {content of block}". 
So if you have 'body{color:red;' with a missing closing bracket, the error will be " 'Missing '}' after color:red;". However, it will not show the error however if there is *no content at all* in the block, like in your example. So the intended behavior is to not show the error.

The reason the keyed object does result in an error is that when using a keyed object cleancss will actually concatenate all source files (in source-reader.js) before passing it to the clean-css core. To track the original files, each file in the concatenated source is wrapped in special tokens (\_\_ESCAPED_SOURCE_CLEAN_CSS0\_\_ and \_\_ESCAPED_SOURCE_END_CLEAN_CSS\_\_, where 0 is the file index). So the code passed to the tokenizer is actually \_\_ESCAPED_SOURCE_CLEAN_CSS0\_\_body{\_\_ESCAPED_SOURCE_END_CLEAN_CSS\_\_.

The tokenizer does handle these special escape tokens, but (probably wrongly) doesn't check for these when inside a selector block. Not finding a closing bracket '}' it will show the error message if there is text (css attributes) in the block. Having failing to parse the escape token correctly it treats it as text and shows it in the error message.

**Comment by scniro** [comment] 2016-12-07 18:21
ah thanks for the explanation and I can see now your example of `'body{color:red;'` as a _raw string_ indeed works and returns the expected error. Your explanation on the empty content also makes sense, however, I can still force different results based _only_ on the parameter type passed with the exact same content. Observe the following example...

```
const CleanCSS = require('clean-css');

var css = {};
css['foo'] = { styles: 'body{' };

// returns error
new CleanCSS().minify(css, function (errors, css) {
  console.log('object passed: ', css.warnings)
});

// no error
new CleanCSS().minify('body{', function (errors, css) {
  console.log('raw passed: ', css.warnings)
});
```

which, bizarrely, returns two totally different results...

 > object passed:  [ 'Missing \'}\' after \'__ESCAPED_SOURCE_END_CLEAN_CSS__\'. Ignoring.' ]

with the raw style string passed I get...

> raw passed:  []

both have the same content of `body{`

huh?! Maybe an issue for clean-css itself. I can certainly publish a new version which only accepts the new string, but I'd really like some insight on this one first...

**Comment by madwizard-thomas** [comment] 2016-12-07 18:57
You are right that with an empty body tag you get different results, but I see this as a bug in the clean-css tokenizer:
See https://github.com/jakubpawlowicz/clean-css/blob/master/lib/tokenizer/tokenize.js
```javascript
 while (true) {
    var next = whatsNext(context);
    if (!next) {
      var whatsLeft = context.chunk.substring(context.cursor);
      if (whatsLeft.trim().length > 0) {
        if (context.mode == 'body') {
          context.warnings.push('Missing \'}\' after \'' + whatsLeft + '\'. Ignoring.');
        } else {
          tokenized.push(['text', [whatsLeft]]);
        }
        context.cursor += whatsLeft.length;
      }
      break;
}
```
After parsing "body{", the tokenizer is in body mode (i.e. context.mode=='body', note that 'body' here is unrelated to the tag name, it means the body of a css declaration), the whatsNext function is only looking for '}' in this mode. Because there is no closing bracket, whatsNext returns null. 
whatsLeft is the text after the last parsed part, meaning the content of the body text. 
If this string is something like 'color:red;' the error is shown. If it is not empty, it warns that it will ignore the contents of the body tag. If it is empty, no error is shown because basically no harm is done, there was nothing inside the tag anyway. So the correct behavior is to not show the error in your case.

The error you get is caused because whatsNext does not recognize the special ESCAPED_SOURCE string, and this wrongly ends up as normal text in 'whatsLeft'.

So this is an issue with clean-css itself, you can find more issues with this special tag on their github page (though different cases I think they are caused by the same thing).

**Comment by scniro** [comment] 2016-12-08 00:30
I see! Okay, so I corrected my test to actually now test your example of `body{color:red`, and everything else _seems_ okay. Published [2.1.2](https://www.npmjs.com/package/gulp-clean-css), can you install and let me know if okie dokie?

**Comment by scniro** [comment] 2016-12-08 02:56
whirlwind of stuff today, try 2.1.3 please

**Comment by madwizard-thomas** [comment] 2016-12-08 09:41
Thanks, it seems to work fine now!

**Comment by scniro** [comment] 2016-12-08 14:27
@madwizard-thomas awesome thanks for being so helpful!. @buddyackerman could you install latest and let us know if this fixed your issue as well?

**Closed** 2016-12-09 13:29 UTC

**Comment by scniro** [comment] 2016-12-15 14:39
@madwizard-thomas @biomedia-thomas (in case I miss you on the other one) If you were at all interested, #22 seems to have an issue with the solution here. There seems to be a need for the `cssFile[file.path]` approach. If you have the time, could you please glance at this issue thread and see if anything jumps out at you? The OP mentioned you may have overlooked certain options passed to cleancss, which perhaps could have alleviated the initial problem on here in the first place.
